require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true

  Exclude:
  - 'bin/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - 'config/initializers/*'
  - 'spec/factories/*'
  - 'node_modules/**/*'

# TODO: Reduce method complexity in omniauth callback controller.
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'lib/tasks/ci.rake'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'config/routes.rb'
    - 'lib/tasks/pulmap.rake'
    - 'lib/tasks/thumbnails.rake'
    - 'spec/**/*'

Metrics/BlockNesting:
  Exclude:
    - 'app/helpers/advanced_helper.rb'

Metrics/ClassLength:
  Max: 100
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/advanced_helper.rb'

Metrics/LineLength:
  Max: 125
  Exclude:
    - 'Rakefile'
    # TODO: Refactor add_show_tools_partial procs.
    - 'app/controllers/catalog_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'config/deploy.rb'
    - 'lib/tasks/pulmap.rake'
    - 'lib/tasks/thumbnails.rake'
    - 'spec/lib/thumbnail_spec.rb'
    - 'spec/requests/advanced_request_spec.rb'
    - 'spec/services/robots_generator_service_spec.rb'

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'app/helpers/advanced_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/advanced_helper.rb'

# TODO: Add top-level class and module documentation.
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# Overrides method in blacklight. Must use method name.
Naming/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Rails/Output:
  Exclude:
    - 'config/deploy.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/pulmap_geoblacklight_helper.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
