require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

  Exclude:
  - 'bin/*'
  - 'config/initializers/*'
  - 'db/**/*'
  - 'node_modules/**/*'
  - 'spec/factories/*'
  - 'tmp/**/*'
  - 'vendor/**/*'

Layout/HashAlignment:
  Exclude:
    - 'app/helpers/pulmap_geoblacklight_helper.rb'

Layout/LineLength:
  Max: 125
  Exclude:
    - 'Rakefile'
    # TODO: Refactor add_show_tools_partial procs.
    - 'app/controllers/catalog_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/pulmap_geoblacklight_helper.rb'
    - 'config/deploy.rb'
    - 'lib/tasks/pulmap.rake'
    - 'lib/tasks/thumbnails.rake'
    - 'spec/lib/thumbnail_spec.rb'
    - 'spec/requests/advanced_request_spec.rb'
    - 'spec/services/robots_generator_service_spec.rb'
    - 'spec/views/catalog/_web_services.erb_spec.rb'
    - 'spec/controllers/thumbnails_controller_spec.rb'
    - 'spec/requests/geoserver_requests_spec.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/pulmap_geoblacklight_helper.rb'
    - 'lib/tasks/ci.rake'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'config/routes.rb'
    - 'lib/tasks/pulmap.rake'
    - 'lib/tasks/thumbnails.rake'
    - 'spec/**/*'

Metrics/BlockNesting:
  Exclude:
    - 'app/helpers/advanced_helper.rb'

Metrics/ClassLength:
  Max: 100
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/pulmap_geoblacklight_helper.rb'
    - 'app/controllers/geoserver_controller.rb'

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/pulmap_geoblacklight_helper.rb'
    - 'app/controllers/geoserver_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/pulmap_geoblacklight_helper.rb'

# Overrides method in blacklight. Must use method name.
Naming/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Rails/Output:
  Exclude:
    - 'config/deploy.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/pulmap_geoblacklight_helper.rb'

Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/pulmap.rake'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
