# frozen_string_literal: true

source "https://rubygems.org", cooldown: 14

gem "autoprefixer-rails"
# Pin to prevent passenger error
gem "base64", "0.3.0"
gem "blacklight", "7.42"
gem "blacklight_range_limit"
gem "bootstrap", "~> 4.0"
gem "capistrano"
gem "capistrano-bundler"
gem "capistrano-passenger"
gem "capistrano-rails"
gem "capistrano-rails-console"
gem "connection_pool", "< 4"
gem "csv"
gem "datadog"
gem "devise", "~> 5.0"
gem "devise-guests"
gem "faraday"
gem "font-awesome-rails"
gem "geoblacklight", "4.5.1"
gem "geoblacklight_sidecar_images", "1.1.2"
gem "geo_combine"
gem "google-cloud-storage", "~> 1.11"
gem "health-monitor-rails"
gem "honeybadger"
gem "jquery-rails"
gem "lograge"
gem "logstash-event"
gem "loofah"
gem "mail_form"
gem "mimemagic", "0.3.10"
gem "modernizr-rails"
gem "omniauth-cas", "~> 2.0"
gem "omniauth-rails_csrf_protection", "~> 0.1"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-all"
gem "opentelemetry-sdk"
gem "pg"
gem "puma"
gem "rack"
gem "rails", "~> 8.1"
gem "rake", ">= 13"
gem "redis"
gem "rsolr"
gem "sassc-rails"
gem "sidekiq"
gem "simple_form"
gem "sitemap_generator"
gem "sneakers", "~> 2.11.0"
gem "turbolinks"
gem "twitter-typeahead-rails"
gem "vite_rails"
gem "whenever"

group :development, :test do
  gem "capybara"
  gem "capybara-screenshot"
  gem "database_cleaner"
  gem "factory_bot_rails"
  gem "pry-byebug"
  gem "rails-controller-testing"
  gem "rspec-rails"
  gem "rubocop-rails-omakase"
  gem "simplecov"
  gem "spring"
end

group :development do
  gem "bcrypt_pbkdf"
  gem "ed25519"
  gem "web-console"
end

group :test do
  gem "axe-core-rspec"
  gem "selenium-webdriver"
  gem "timecop"
  gem "webmock"
end
