# frozen_string_literal: true

source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'coffee-rails'
gem 'ddtrace'
gem 'jbuilder'
gem 'jquery-rails'
gem 'lograge'
gem 'logstash-event'
gem 'loofah', '>= 2.2.3'
gem 'modernizr-rails'
gem 'pg', '~> 1.0'
gem 'puma', '~> 5.0'
gem 'rack', '>= 2.0.6'
gem 'rails', '~> 5.2'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'bixby'
  gem 'byebug'
  gem 'capybara'
  gem 'coveralls', require: false
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'pry-byebug'
  gem 'rails-controller-testing'
  gem 'rspec-rails', '~> 3.5'
  gem 'spring'
  gem 'webdrivers'
end

group :development do
  gem 'web-console', '~> 3.7.0'
end

gem 'blacklight_advanced_search', '~> 7.0.0'
gem 'blacklight_range_limit'
gem 'bootstrap'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-passenger'
gem 'capistrano-rails'
gem 'devise', '~> 4.7.1'
gem 'devise-guests'
gem 'font-awesome-rails'
gem 'geo_combine', '~> 0.5'
gem 'geoblacklight', '~> 3.0'
gem 'geoblacklight_sidecar_images', git: 'https://github.com/pulibrary/geoblacklight_sidecar_images.git', branch: 'gbl-3'
gem 'geoserver-worker', git: 'https://github.com/pulibrary/geoserver-worker', branch: 'master'
gem 'google-cloud-storage', '~> 1.11'
gem 'honeybadger'
gem 'mail_form'
gem 'omniauth-cas'
gem 'omniauth-rails_csrf_protection', '~> 0.1'
gem 'rsolr', '~> 1.1.1'
gem 'sidekiq'
gem 'simple_form'
gem 'sitemap_generator', '~> 6.0'
gem 'sneakers'
gem 'twitter-typeahead-rails'
gem 'webpacker'
gem 'whenever'
