source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'coffee-rails'
gem 'ddtrace'
gem 'jbuilder'
gem 'jquery-rails'
gem 'lograge'
gem 'logstash-event'
gem 'loofah', '>= 2.2.3'
gem 'modernizr-rails'
gem 'pg', '~> 1.0'
gem 'puma'
gem 'rack', '>= 2.0.6'
gem 'rails', '~> 5.2'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'coveralls', require: false
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'pry-byebug'
  gem 'rails-controller-testing'
  gem 'rspec-rails', '~> 3.5'
  gem 'rubocop', '~> 0.51.0', require: false
  gem 'rubocop-rspec', '~> 1.20', require: false
  gem 'spring'
  gem 'webdrivers'
end

group :development do
  gem 'web-console'
end

gem 'blacklight_advanced_search'
gem 'blacklight_range_limit'
gem 'bootstrap-sass', '~> 3.4'
gem 'bourbon', '4.3.4'
gem 'capistrano', '~> 3.7.1'
gem 'capistrano-bundler'
gem 'capistrano-passenger'
gem 'capistrano-rails'
gem 'chosen-rails' #  jquery multiselect plugin for advanced search
gem 'devise', '~> 4.6.0'
gem 'devise-guests'
gem 'geoblacklight', '~> 1.9.1'
gem 'geoserver-worker', git: 'https://github.com/pulibrary/geoserver-worker', branch: 'master'
gem 'honeybadger'
gem 'mail_form'
gem 'neat', '~> 1.8'
gem 'omniauth-cas'
gem 'pul_uv_rails', git: 'https://github.com/pulibrary/pul_uv_rails', branch: 'master'
gem 'rails-reverse-proxy'
gem 'rsolr', '~> 1.1.1'
gem 'sidekiq'
gem 'simple_form'
gem 'sitemap_generator', '~> 6.0'
gem 'sneakers'
gem 'solr_wrapper'
gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'
gem 'webpacker'
