defaults: &defaults
  events:
    server: 'amqp://localhost:5672'
    exchange: 'gbl_events'
  leaflet_geocoder:
    provider:
      name: <%= ENV['LEAFLET_GEOCODER_PROVIDER'] || 'OpenStreetMap' %>
      key: <%= ENV['LEAFLET_GEOCODER_KEY'] || 'secret' %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  events:
    server: <%= ENV['PULMAP_RABBIT_SERVER'] || 'amqp://localhost:5672' %>
    exchange: 'gbl_events'

staging:
  <<: *defaults
  events:
    server: <%= ENV['PULMAP_RABBIT_SERVER'] || 'amqp://localhost:5672' %>
    exchange: 'gbl_events'
